name: Deploy my-strapi-app

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: my-strapi-app
  CODEDEPLOY_APP: my-strapi-app
  CODEDEPLOY_GROUP: my-strapi-app-dg

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
      id: ecr

    - name: Build Docker image
      run: docker build -t my-strapi-app -f my-strapi-app/Dockerfile my-strapi-app

    - name: Tag image
      run: |
        docker tag my-strapi-app:latest \
        ${{ steps.ecr.outputs.registry }}/my-strapi-app:latest

    - name: Push image
      run: |
        docker push \
        ${{ steps.ecr.outputs.registry }}/my-strapi-app:latest

    - name: Update task definition
      run: |
        sed -i "s|IMAGE_URI|${{ steps.ecr.outputs.registry }}/my-strapi-app:latest|g" taskdef.json

    - name: Register task definition
      run: |
        TASK=$(aws ecs register-task-definition \
          --cli-input-json file://taskdef.json \
          --query taskDefinition.taskDefinitionArn \
          --output text)
        echo "TASK_DEFINITION=$TASK"
        sed -i "s|TASK_DEFINITION|$TASK|g" appspec.yaml

    - name: Deploy via CodeDeploy
      run: |
        CONTENT=$(base64 -w 0 appspec.yaml)
        SHA=$(sha256sum appspec.yaml | awk '{print $1}')

        aws deploy create-deployment \
          --application-name $CODEDEPLOY_APP \
          --deployment-group-name $CODEDEPLOY_GROUP \
          --revision revisionType=AppSpecContent,appSpecContent="{content=$CONTENT,sha256=$SHA}"
