name: Deploy my-strapi-app

on:
  push:
    branches: [ main ]

env:

  AWS_REGION: ap-south-1
  ECR_REPOSITORY: my-strapi-app
  CODEDEPLOY_APP: my-strapi-app
  CODEDEPLOY_GROUP: my-strapi-app-dg

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - uses: aws-actions/amazon-ecr-login@v2
      id: ecr

    - name: Build
      run: |
        docker build -t my-strapi-app ./app

    - name: Tag
      run: |
        docker tag my-strapi-app:latest \
        ${{ steps.ecr.outputs.registry }}/my-strapi-app:latest

    - name: Push
      run: |
        docker push \
        ${{ steps.ecr.outputs.registry }}/my-strapi-app:latest

    - name: Update taskdef
      run: |
        sed -i "s|IMAGE_URI|${{ steps.ecr.outputs.registry }}/my-strapi-app:latest|g" taskdef.json

    - name: Register task
      run: |
        TASK=$(aws ecs register-task-definition \
        --cli-input-json file://taskdef.json \
        --query taskDefinition.taskDefinitionArn \
        --output text)

        sed -i "s|TASK_DEFINITION|$TASK|g" appspec.yaml

    - name: Deploy
      run: |
        aws deploy create-deployment \
        --application-name my-strapi-app \
        --deployment-group-name my-strapi-app-dg \
        --revision revisionType=AppSpecContent,appSpecContent="{content='$(cat appspec.yaml | base64 -w 0)',sha256=$(sha256sum appspec.yaml | awk '{print $1}')}"
